name: Github Action

on:
  push:
    branches: [ develop ]

jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    
    steps:
      - run: echo "Hello World !"
      - name: Check the Repository files
        uses: actions/checkout@v2
      - name: Using Node js version 14.x
        uses: actions/setup-node@v1
        with:
          node-version: '14'
      - name: installing NPM packages
        run: npm install
      - name: Building Next js Application
        run: npm run build